Issue126
NREL/hive pull request #174
Opened 2023-04-24 21:54 UTC by jkirsh2

- added cumulative energy delta tracking to vehicles and stations
- include energy dispensed/expended in summary report

2023-04-24 22:36 UTC, robfitzgerald requested changes
looks great. so satisfying to see this now in the logs:

```
│ Total kWh Expended By Vehicles               │ 676.09 kWh │
│ Total Gasoline Expended By Vehicles          │ 70.24 Gal  │
│ Total kWh Dispensed By Stations              │ 872.03 kWh │
│ Total Gasoline Dispensed By Stations         │ 7.0 Gal    │
```

a few minor requests to wrap {}'s in Map(). thank you!

2023-04-24 22:36 UTC, robfitzgerald commented on nrel/hive/model/station/station.py
> +        energy_dispensed = {
wrap with immutables.Map

2023-04-24 22:36 UTC, robfitzgerald commented on nrel/hive/model/vehicle/vehicle.py
> +        energy_expended = {k: self.energy_expended[k] + delta_energy[k] for k in self.energy.keys()}
wrap with immutables.Map

2023-04-24 22:36 UTC, robfitzgerald commented on nrel/hive/model/vehicle/vehicle.py
> +        energy_gained = {k: self.energy_gained[k] + delta_energy[k] for k in self.energy.keys()}
ditto

2023-04-24 23:25 UTC, jhoshiko commented
I wrapped the dictionaries since the two volunteers working on this had to leave, but we'll need to reformat `vehicle.py` and `station.py` with black since I can't do that through github's file editor. Talking with the team, it might make sense to add running black automatically with a pre-commit hook.

2023-04-25 14:40 UTC, robfitzgerald commented
i'll take a stab at fixing this, likely pushing up a new PR with the changes + formatting

2023-04-25 15:00 UTC, nreinicke commented
Closing as this was included in #179

2023-04-25 15:00 UTC, closed without merging